/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:847fc7dc-f140-4681-aa40-93e3a712e23c",
    "aws_cognito_region": "ap-southeast-1",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_dev",
            "alias": "$LATEST",
            "region": "ap-southeast-1"
        },
        {
            "name": "easyhealth_dev",
            "alias": "$LATEST",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
